### ISSUE TITLE
Add support for big FPGAs

### ISSUE THREAD

**Issue by mnemocron** [LDprg/XDC#2]
Very nice package, thank you.

However, my FPGA is so large that the Pin descriptions can start with 2 alpha characters.
The highlighter treats this as a single character only.
See screenshot L87 ff.

![image](https://user-images.githubusercontent.com/13417604/157039593-61b67020-f2bf-4934-951e-7e16f2f82155.png)

**Comment by LDprg** [comment]
Thanks for reporting this, I fixed it.
